# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cipher.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cipher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ipher.proto\x12\tcipher.v1\"4\n\x0e\x45ncryptRequest\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"5\n\x0f\x45ncryptResponse\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\x12\x0e\n\x06key_id\x18\x02 \x01(\t\"E\n\x0e\x44\x65\x63ryptRequest\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\x0e\n\x06key_id\x18\x03 \x01(\t\"$\n\x0f\x44\x65\x63ryptResponse\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\"D\n\rRewrapRequest\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\x0e\n\x06key_id\x18\x03 \x01(\t\"4\n\x0eRewrapResponse\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\x12\x0e\n\x06key_id\x18\x02 \x01(\t\"\r\n\x0bKeysRequest\"<\n\x0cKeysResponse\x12\x15\n\ractive_key_id\x18\x01 \x01(\t\x12\x15\n\rknown_key_ids\x18\x02 \x03(\t2\x8b\x02\n\rCipherService\x12@\n\x07\x45ncrypt\x12\x19.cipher.v1.EncryptRequest\x1a\x1a.cipher.v1.EncryptResponse\x12@\n\x07\x44\x65\x63rypt\x12\x19.cipher.v1.DecryptRequest\x1a\x1a.cipher.v1.DecryptResponse\x12=\n\x06Rewrap\x12\x18.cipher.v1.RewrapRequest\x1a\x19.cipher.v1.RewrapResponse\x12\x37\n\x04Keys\x12\x16.cipher.v1.KeysRequest\x1a\x17.cipher.v1.KeysResponseB:\n\x1c\x63om.mcpcipher.grpc.cipher.v1P\x01Z\x18mcp-cipher/pkg/pb/cipherb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cipher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.mcpcipher.grpc.cipher.v1P\001Z\030mcp-cipher/pkg/pb/cipher'
  _globals['_ENCRYPTREQUEST']._serialized_start=27
  _globals['_ENCRYPTREQUEST']._serialized_end=79
  _globals['_ENCRYPTRESPONSE']._serialized_start=81
  _globals['_ENCRYPTRESPONSE']._serialized_end=134
  _globals['_DECRYPTREQUEST']._serialized_start=136
  _globals['_DECRYPTREQUEST']._serialized_end=205
  _globals['_DECRYPTRESPONSE']._serialized_start=207
  _globals['_DECRYPTRESPONSE']._serialized_end=243
  _globals['_REWRAPREQUEST']._serialized_start=245
  _globals['_REWRAPREQUEST']._serialized_end=313
  _globals['_REWRAPRESPONSE']._serialized_start=315
  _globals['_REWRAPRESPONSE']._serialized_end=367
  _globals['_KEYSREQUEST']._serialized_start=369
  _globals['_KEYSREQUEST']._serialized_end=382
  _globals['_KEYSRESPONSE']._serialized_start=384
  _globals['_KEYSRESPONSE']._serialized_end=444
  _globals['_CIPHERSERVICE']._serialized_start=447
  _globals['_CIPHERSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
