# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.pb import cipher_pb2 as cipher__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cipher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CipherServiceStub:
    """Encrypts and decrypts the secrets the MCP stack stores.

    The point of a separate service is that the keys live in exactly one process. Callers
    hold ciphertext and a key id; none of them can read a value without asking, and none of
    them has to be trusted with a key in order to store one.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encrypt = channel.unary_unary(
                '/cipher.v1.CipherService/Encrypt',
                request_serializer=cipher__pb2.EncryptRequest.SerializeToString,
                response_deserializer=cipher__pb2.EncryptResponse.FromString,
                _registered_method=True)
        self.Decrypt = channel.unary_unary(
                '/cipher.v1.CipherService/Decrypt',
                request_serializer=cipher__pb2.DecryptRequest.SerializeToString,
                response_deserializer=cipher__pb2.DecryptResponse.FromString,
                _registered_method=True)
        self.Rewrap = channel.unary_unary(
                '/cipher.v1.CipherService/Rewrap',
                request_serializer=cipher__pb2.RewrapRequest.SerializeToString,
                response_deserializer=cipher__pb2.RewrapResponse.FromString,
                _registered_method=True)
        self.Keys = channel.unary_unary(
                '/cipher.v1.CipherService/Keys',
                request_serializer=cipher__pb2.KeysRequest.SerializeToString,
                response_deserializer=cipher__pb2.KeysResponse.FromString,
                _registered_method=True)


class CipherServiceServicer:
    """Encrypts and decrypts the secrets the MCP stack stores.

    The point of a separate service is that the keys live in exactly one process. Callers
    hold ciphertext and a key id; none of them can read a value without asking, and none of
    them has to be trusted with a key in order to store one.
    """

    def Encrypt(self, request, context):
        """Encrypts with the currently active key. The reply names the key that was used, and
        the caller stores that alongside the ciphertext.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decrypt(self, request, context):
        """Decrypts with the key the ciphertext was sealed under. A key that has been retired
        for encryption can still decrypt, which is what makes rotation possible without
        rewriting every stored value at once.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rewrap(self, request, context):
        """Re-seals a value under the active key. Used to migrate stored values off a retired
        key; the plaintext never leaves this service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Keys(self, request, context):
        """Which key new values are sealed under, and which ones can still be opened.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CipherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Encrypt,
                    request_deserializer=cipher__pb2.EncryptRequest.FromString,
                    response_serializer=cipher__pb2.EncryptResponse.SerializeToString,
            ),
            'Decrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Decrypt,
                    request_deserializer=cipher__pb2.DecryptRequest.FromString,
                    response_serializer=cipher__pb2.DecryptResponse.SerializeToString,
            ),
            'Rewrap': grpc.unary_unary_rpc_method_handler(
                    servicer.Rewrap,
                    request_deserializer=cipher__pb2.RewrapRequest.FromString,
                    response_serializer=cipher__pb2.RewrapResponse.SerializeToString,
            ),
            'Keys': grpc.unary_unary_rpc_method_handler(
                    servicer.Keys,
                    request_deserializer=cipher__pb2.KeysRequest.FromString,
                    response_serializer=cipher__pb2.KeysResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cipher.v1.CipherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cipher.v1.CipherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CipherService:
    """Encrypts and decrypts the secrets the MCP stack stores.

    The point of a separate service is that the keys live in exactly one process. Callers
    hold ciphertext and a key id; none of them can read a value without asking, and none of
    them has to be trusted with a key in order to store one.
    """

    @staticmethod
    def Encrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.v1.CipherService/Encrypt',
            cipher__pb2.EncryptRequest.SerializeToString,
            cipher__pb2.EncryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.v1.CipherService/Decrypt',
            cipher__pb2.DecryptRequest.SerializeToString,
            cipher__pb2.DecryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rewrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.v1.CipherService/Rewrap',
            cipher__pb2.RewrapRequest.SerializeToString,
            cipher__pb2.RewrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Keys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.v1.CipherService/Keys',
            cipher__pb2.KeysRequest.SerializeToString,
            cipher__pb2.KeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
